### ISSUE TITLE
Undefined class constant 'SKIPPED'

### ISSUE THREAD

**Issue by peterpp** [jiripudil/intellij-nette-tester#33] opened 2017-06-15 14:30 UTC
I've updated plugin from alpha.4 to beta.2 and changed

```
"require-dev": {
	"nette/tester": "dev-feature/teamcity-output"
},
```

to `"nette/tester": "@dev"`

Now, I get error:

Fatal error: Undefined class constant 'SKIPPED' in .../PhpStorm2017.1/intellij-nette-tester/setup.php on line 39

**Comment by jiripudil** [comment] 2017-06-15 14:40
Duplicate of #30, in short: Nette Tester dev-master is not (yet?) supported. Please stick to 1.x stable release until it is resolved. Sorry for the inconvenience 🙁

**Closed by jiripudil** 2017-06-15 14:40 UTC

**Comment by peterpp** [comment] 2017-06-15 14:45
Today I'm really blind 🙈
